version: '3.4'

services:
  stonehugin:
    image: cdd
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: cddcontroler
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./cdd/database/creator.sql:/docker-entrypoint-initdb.d/creator.sql
      - ./cdd/database/populate.sql:/docker-entrypoint-initdb.d/populate.sql
  
volumes:
  database-data: