INSERT INTO public.stocks (stock_base, stock_value) VALUES ('AC - RIO BRANCO' ::text, ' 379'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('AL - MACEIO' ::text, ' 98'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('AM - MANAUS' ::text, ' 220'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('AP - MACAPA' ::text, ' 116'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('BA - ALAGOINHAS' ::text, ' 49'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('BA - BUNKER SALVADOR' ::text, ' 371'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('BA - FEIRA DE SANTANA' ::text, ' 132'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('BA - VITORIA DA CONQUISTA' ::text, ' 242'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('CE - CASCAVEL' ::text, ' 153'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('CE - FORTALEZA' ::text, ' 236'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('CE - JUAZEIRO DO NORTE' ::text, ' 399'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('CE - SOBRAL' ::text, ' 362'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('DF - BRASILIA' ::text, ' 304'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('DF - PLANALTINA' ::text, ' 299'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('ES - ARACRUZ' ::text, ' 100'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('ES - CACHOEIRO DE ITAPEMIRIM' ::text, ' 287'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('ES - GUARAPARI' ::text, ' 304'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('ES - VITORIA' ::text, ' 160'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('GO - CATALAO' ::text, ' 187'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('GO - GOIANIA' ::text, ' 396'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('GO - ITUMBIARA' ::text, ' 286'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('GO - RIO VERDE' ::text, ' 153'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('GO - VALPARAISO DE GOIAS' ::text, ' 28'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MA - SAO LUIS' ::text, ' 193'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MG - ALFENAS' ::text, ' 33'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MG - BELO HORIZONTE' ::text, ' 94'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MG - JUIZ DE FORA' ::text, ' 185'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MG - PATOS DE MINAS' ::text, ' 367'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MG - POÃ‡OS DE CALDAS' ::text, ' 75'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MG - POUSO ALEGRE' ::text, ' 36'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MS - CAMPO GRANDE' ::text, ' 66'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MS - DOURADOS' ::text, ' 274'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MT - CUIABA' ::text, ' 241'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('MT - PRIMAVERA DO LESTE' ::text, ' 277'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PA - CASTANHAL' ::text, ' 299'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PA - MARABA' ::text, ' 52'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PB - CAMPINA GRANDE' ::text, ' 360'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PB - JOAO PESSOA' ::text, ' 12'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PB - PATOS' ::text, ' 130'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PE - BUNKER RECIFE 1' ::text, ' 58'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PE - CARUARU' ::text, ' 130'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PE - GRAVATA' ::text, ' 309'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PE - JABOATAO DOS GUARARAPES' ::text, ' 336'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PE - OLINDA' ::text, ' 293'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PE - VALE DO SAO FRANCISCO' ::text, ' 358'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PI - TERESINA' ::text, ' 322'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PR - APUCARANA' ::text, ' 394'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PR - CURITIBA' ::text, ' 17'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PR - FOZ DO IGUAÃ‡U' ::text, ' 80'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PR - LONDRINA' ::text, ' 365'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('PR - MARINGA' ::text, ' 11'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - BANGU' ::text, ' 258'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - BUNKER 1' ::text, ' 280'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - CABO FRIO' ::text, ' 299'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - CAMPO GRANDE' ::text, ' 73'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - CAMPOS' ::text, ' 167'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - DUQUE DE CAXIAS' ::text, ' 393'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - ITAPERUNA' ::text, ' 368'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - MACAE' ::text, ' 239'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - NITEROI' ::text, ' 72'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - RECREIO' ::text, ' 60'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - RESENDE' ::text, ' 125'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - RIO DAS OSTRAS' ::text, ' 156'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - SANTA CRUZ' ::text, ' 224'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - SAO GONÃ‡ALO' ::text, ' 240'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - SAQUAREMA' ::text, ' 173'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RJ - VOLTA REDONDA' ::text, ' 360'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RN - NATAL' ::text, ' 344'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RO - PORTO VELHO' ::text, ' 388'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('RS - CAXIAS DO SUL' ::text, ' 137'::integer);
INSERT INTO public.stocks (stock_base, stock_value) VALUES ('SC - BLUMENAU' ::text, ' 199'::integer);

INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PE - CARUARU'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-02'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'BA - VITORIA DA CONQUISTA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'PR - MARINGA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-05'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-07'::date, 'RJ - RIO DAS OSTRAS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'RJ - MACAE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-02'::date, 'GO - VALPARAISO DE GOIAS'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'AC - RIO BRANCO'::text, 'AC'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'BA - FEIRA DE SANTANA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'RJ - CAMPOS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-17'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - RECREIO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'GO - VALPARAISO DE GOIAS'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'GO - ITUMBIARA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-09'::date, 'AC - RIO BRANCO'::text, 'AC'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'GO - VALPARAISO DE GOIAS'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'MG - JUIZ DE FORA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-04-02'::date, 'DF - PLANALTINA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'BA - VITORIA DA CONQUISTA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'GO - VALPARAISO DE GOIAS'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'BA - ALAGOINHAS'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'BA - FEIRA DE SANTANA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'RJ - NITEROI'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'PA - MARABA'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RS - CAXIAS DO SUL'::text, 'RS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'AL - MACEIO'::text, 'AL'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'MT - CUIABA'::text, 'MT'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - NITEROI'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'ES - GUARAPARI'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-09'::date, 'AL - MACEIO'::text, 'AL'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'CE - JUAZEIRO DO NORTE'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'CE - CASCAVEL'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'AC - RIO BRANCO'::text, 'AC'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'MA - SAO LUIS'::text, 'MA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - RECREIO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'MG - POÃ‡OS DE CALDAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'RJ - NITEROI'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'BA - ALAGOINHAS'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BANGU'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'ES - ARACRUZ'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'AL - MACEIO'::text, 'AL'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PI - TERESINA'::text, 'PI'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PR - MARINGA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RS - CAXIAS DO SUL'::text, 'RS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-16'::date, 'PR - APUCARANA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-18'::date, 'PI - TERESINA'::text, 'PI'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PR - LONDRINA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - CAMPOS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - SAO GONÃ‡ALO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PE - CARUARU'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'AC - RIO BRANCO'::text, 'AC'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'MG - PATOS DE MINAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'RJ - SAO GONÃ‡ALO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-31'::date, 'GO - VALPARAISO DE GOIAS'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'MG - JUIZ DE FORA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-04'::date, 'PE - GRAVATA'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-11'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-02'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-09'::date, 'MG - JUIZ DE FORA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-02'::date, 'RJ - SAO GONÃ‡ALO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-07'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'GO - CATALAO'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - BANGU'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - RESENDE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MT - CUIABA'::text, 'MT'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-07'::date, 'AL - MACEIO'::text, 'AL'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'ES - GUARAPARI'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-26'::date, 'PE - BUNKER RECIFE 1'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-26'::date, 'PE - BUNKER RECIFE 1'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - MACAE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'PE - VALE DO SAO FRANCISCO'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PE - BUNKER RECIFE 1'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'PI - TERESINA'::text, 'PI'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-16'::date, 'BA - FEIRA DE SANTANA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'MS - CAMPO GRANDE'::text, 'MS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - RECREIO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PR - APUCARANA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - JUIZ DE FORA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - RESENDE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-07'::date, 'PR - MARINGA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-12'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-08'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-10'::date, 'PB - CAMPINA GRANDE'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - PATOS DE MINAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'DF - PLANALTINA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'DF - PLANALTINA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'BA - FEIRA DE SANTANA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'MG - PATOS DE MINAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'MG - PATOS DE MINAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - MACAE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - NITEROI'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-11'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'MS - DOURADOS'::text, 'MS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'MG - ALFENAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'MG - ALFENAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'CE - JUAZEIRO DO NORTE'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'RJ - CAMPOS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'DF - PLANALTINA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'BA - VITORIA DA CONQUISTA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'MG - POÃ‡OS DE CALDAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'RJ - MACAE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - SAQUAREMA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PB - CAMPINA GRANDE'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'CE - SOBRAL'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PI - TERESINA'::text, 'PI'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PA - CASTANHAL'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PA - CASTANHAL'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-07'::date, 'PE - VALE DO SAO FRANCISCO'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'PB - CAMPINA GRANDE'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - BANGU'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-02'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-11'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-18'::date, 'BA - BUNKER SALVADOR'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'RJ - RIO DAS OSTRAS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'ES - ARACRUZ'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'RJ - CAMPO GRANDE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-16'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'DF - PLANALTINA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'MA - SAO LUIS'::text, 'MA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'RJ - CABO FRIO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-17'::date, 'RJ - ITAPERUNA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-17'::date, 'RJ - ITAPERUNA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-16'::date, 'PE - BUNKER RECIFE 1'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-02'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'MA - SAO LUIS'::text, 'MA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'MA - SAO LUIS'::text, 'MA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - SAO GONÃ‡ALO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - SAO GONÃ‡ALO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'PR - LONDRINA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'DF - PLANALTINA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'CE - JUAZEIRO DO NORTE'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PE - CARUARU'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - SAQUAREMA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'CE - SOBRAL'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - MACAE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'GO - RIO VERDE'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'GO - RIO VERDE'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'CE - SOBRAL'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'RJ - SAO GONÃ‡ALO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-17'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'PE - BUNKER RECIFE 1'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'DF - PLANALTINA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'PE - VALE DO SAO FRANCISCO'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'BA - BUNKER SALVADOR'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'GO - VALPARAISO DE GOIAS'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'PR - FOZ DO IGUAÃ‡U'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'PR - FOZ DO IGUAÃ‡U'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'MA - SAO LUIS'::text, 'MA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'MA - SAO LUIS'::text, 'MA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-17'::date, 'PR - APUCARANA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'MS - DOURADOS'::text, 'MS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'DF - PLANALTINA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'PI - TERESINA'::text, 'PI'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'MS - DOURADOS'::text, 'MS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-31'::date, 'MA - SAO LUIS'::text, 'MA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'MS - DOURADOS'::text, 'MS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'RJ - RIO DAS OSTRAS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'AL - MACEIO'::text, 'AL'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'BA - BUNKER SALVADOR'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - MACAE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'RJ - BANGU'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'GO - VALPARAISO DE GOIAS'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PA - CASTANHAL'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-02'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-06'::date, 'RS - CAXIAS DO SUL'::text, 'RS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'DF - PLANALTINA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'AL - MACEIO'::text, 'AL'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'PE - OLINDA'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - NITEROI'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - NITEROI'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'RJ - NITEROI'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-06'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'MA - SAO LUIS'::text, 'MA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'BA - ALAGOINHAS'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PR - CURITIBA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-31'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - JUIZ DE FORA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-12'::date, 'GO - ITUMBIARA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - JUIZ DE FORA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - CAMPOS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - DUQUE DE CAXIAS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - CAMPOS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MT - CUIABA'::text, 'MT'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PB - JOAO PESSOA'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PE - GRAVATA'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PR - LONDRINA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-08'::date, 'RS - CAXIAS DO SUL'::text, 'RS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'ES - GUARAPARI'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-05'::date, 'GO - RIO VERDE'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-16'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RS - CAXIAS DO SUL'::text, 'RS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'PE - VALE DO SAO FRANCISCO'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-11'::date, 'RJ - NITEROI'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'PR - LONDRINA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PA - MARABA'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-11'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-10'::date, 'PR - MARINGA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'MT - CUIABA'::text, 'MT'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'PE - VALE DO SAO FRANCISCO'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'MT - CUIABA'::text, 'MT'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'MT - CUIABA'::text, 'MT'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'MT - CUIABA'::text, 'MT'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'RJ - RECREIO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'RJ - ITAPERUNA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'RJ - RECREIO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'RJ - RECREIO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-11'::date, 'RJ - ITAPERUNA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'PE - CARUARU'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'PE - CARUARU'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-10'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - JUIZ DE FORA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - CAMPOS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - JUIZ DE FORA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - SAO GONÃ‡ALO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - POUSO ALEGRE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PA - MARABA'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PA - MARABA'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RS - CAXIAS DO SUL'::text, 'RS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'PE - BUNKER RECIFE 1'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-16'::date, 'PE - CARUARU'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'CE - FORTALEZA'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'RJ - ITAPERUNA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PA - CASTANHAL'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'BA - FEIRA DE SANTANA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - CAMPO GRANDE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PA - MARABA'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'BA - FEIRA DE SANTANA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'CE - JUAZEIRO DO NORTE'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'CE - JUAZEIRO DO NORTE'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'PR - LONDRINA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'CE - JUAZEIRO DO NORTE'::text, 'CE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'BA - VITORIA DA CONQUISTA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-07'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'AL - MACEIO'::text, 'AL'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'ES - CACHOEIRO DE ITAPEMIRIM'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'PE - VALE DO SAO FRANCISCO'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'PR - MARINGA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'GO - RIO VERDE'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'PR - MARINGA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'PI - TERESINA'::text, 'PI'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'PR - MARINGA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - SAO GONÃ‡ALO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - SAQUAREMA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'PI - TERESINA'::text, 'PI'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - POÃ‡OS DE CALDAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'PI - TERESINA'::text, 'PI'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RS - CAXIAS DO SUL'::text, 'RS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-01-07'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'BA - VITORIA DA CONQUISTA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - CAMPO GRANDE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PR - LONDRINA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RS - CAXIAS DO SUL'::text, 'RS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RS - CAXIAS DO SUL'::text, 'RS'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'BA - VITORIA DA CONQUISTA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-04'::date, 'MG - POÃ‡OS DE CALDAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'PA - CASTANHAL'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - BANGU'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'PR - LONDRINA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-03'::date, 'ES - GUARAPARI'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'MG - JUIZ DE FORA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PB - CAMPINA GRANDE'::text, 'PB'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'PA - CASTANHAL'::text, 'PA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-07'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - SAO GONÃ‡ALO'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'DF - BRASILIA'::text, 'DF'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - CAMPO GRANDE'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - JUIZ DE FORA'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'MG - BELO HORIZONTE'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'ES - VITORIA'::text, 'ES'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'BA - FEIRA DE SANTANA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'BA - ALAGOINHAS'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'PR - LONDRINA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'AM - MANAUS'::text, 'AM'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-11-29'::date, 'PR - LONDRINA'::text, 'PR'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-15'::date, 'RJ - ITAPERUNA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - SAQUAREMA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-11'::date, 'RJ - ITAPERUNA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'GO - RIO VERDE'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-15'::date, 'PE - JABOATAO DOS GUARARAPES'::text, 'PE'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-02-21'::date, 'BA - BUNKER SALVADOR'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-06-01'::date, 'BA - FEIRA DE SANTANA'::text, 'BA'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - CAMPOS'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-12-02'::date, 'RJ - BUNKER 1'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-13'::date, 'MG - PATOS DE MINAS'::text, 'MG'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2020-03-12'::date, 'GO - GOIANIA'::text, 'GO'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RJ - VOLTA REDONDA'::text, 'RJ'::text, '1'::integer);
INSERT INTO public.tickets (ticket_date, ticket_base, ticket_country_state, ticket_consumption) VALUES ('2019-10-10'::date, 'RN - NATAL'::text, 'RN'::text, '1'::integer);
